from os import getenv
from dotenv import load_dotenv

load_dotenv()

MONGO_DB_HOST = getenv("MONGO_DB_HOST")
MONGO_DB_PORT = getenv("MONGO_DB_PORT")
MONGO_DB_ROOT_USERNAME = getenv("MONGO_DB_ROOT_USERNAME")
MONGO_DB_ROOT_PASSWORD = getenv("MONGO_DB_ROOT_PASSWORD")
MONGO_DB_DATABASE = getenv("MONGO_DB_DATABASE")

DB_URI = f"mongodb://{MONGO_DB_ROOT_USERNAME}:{MONGO_DB_ROOT_PASSWORD}@{MONGO_DB_HOST}:{MONGO_DB_PORT}/"
DB_NAME = MONGO_DB_DATABASE